### ISSUE TITLE
Command Proposal - schedule a message

### ISSUE THREAD

**Issue by MarshallAsch** [Botomir/Botomir#125]
Sometimes you want to schedule a message to happen every once in a while. And so we shall add it. 

The [agenda](https://github.com/agenda/agenda) project seems like it will work well as a backend for this. 
One of the good things about this library is that it has persistence built in so it will make the events persistent across application restarts.

A potential message format could be something like
```
> !schedule every Thursday at 6:00pm
Hey all remember we have DND in an hour!
```

that should make it easy to parse out the date from the message (separated by the first new line)

**Comment by MarshallAsch** [comment]
@SoorajModi I know human readable formats is way easier to use, but do you think that it is fine if we schedule this using a crontab format string?

**Comment by SoorajModi** [comment]
> @SoorajModi I know human readable formats is way easier to use, but do you think that it is fine if we schedule this using a crontab format string?

Sure, as long as we link to instructions on how to use crontab in the documentation
