### ISSUE TITLE
Feature Proposal - Pronoun Reaction Roles

### ISSUE THREAD

**Issue by Kayeris** [Botomir/Botomir#189]
Please add Pronoun Reaction Roles with the following options
- He/Him
- She/Her
- They/Them
- Other

This feature is a part of Botomir's Discord CLI
*Please use the same emojis present in CCubed's Pronoun Reaction Channel

**Comment by MarshallAsch** [comment]
Do you have any visions for associated emojis, custom messages, channel specifications, pronoun options

**Comment by Kayeris** [comment]
Yes, as mentioned in the issue itself, the options for the pronouns and the emojis are as follows:
- She/Her- He/Him- They/Them- Other
The emojis I mentioned are:
For the format of the message, Please leave it in simple list form like the year reaction roles implemented earlier, or like the screenshot above.
Custom Message: Below you can find pronouns that you can assign to yourself! Please react to the pronoun you identify with!



 

    On Saturday, May 15, 2021, 07:58:23 p.m. EDT, Marshall Asch ***@***.***> wrote:  
 
 


Do you have any visions for associated emojis, custom messages, channel specifications, pronoun options

**Comment by MarshallAsch** [comment]
Plan for this, change the role reaction process to lookup the, (guild, channel, message, emoji) and see what role is assigned. This will allow there to be support for multiple role reaction messages sent to different channels. This strategy will have impacts on how updates happen, how the channel it gets sent too is specified and how role reaction messages get deleted. 


Possible solution:

```
!create-role-reaction #channel
<message text>
---
<emoji> :  <role> : <friendly name>
...
```

```
!update-role-reaction <message link>
<message text>
---
<emoji> :  <role> : <friendly name>
```

```
!remove-role-reaction <message link>
```

```
!add-reaction <message link> <emoji> <role>
```

@SoorajModi  thoughts? Almost all of the existing code will still work with this change

**Comment by SoorajModi** [comment]
Hey, I like this change so far, lets keep this change simple and we can plan out a better way to do it in the future.

One question, should remove role reaction be this instead?
```
!remove-role-reaction <message link> <role>
```

**Comment by MarshallAsch** [comment]
> One question, should remove role reaction be this instead?

I think the remove should remove the entire message, if you want to remove one reaction then the message would need to be updated so that can be done with the update command

**Comment by SoorajModi** [comment]
> > One question, should remove role reaction be this instead?
> 
> I think the remove should remove the entire message, if you want to remove one reaction then the message would need to be updated so that can be done with the update command

Okay, that format looks good to me then!
