### ISSUE TITLE
Feature Proposal - Message Edit/Delete Log Channel

### ISSUE THREAD

**Issue by rithik-c** [Botomir/Botomir#207]
Include the following information in your issue:

This feature would allow certain admin roles to have access to a dedicated channel of all message edits and deletes. This would be very useful in moderation and determining if any user is breaking the server rules or discord TOS and simply editing/deleting their messages to get away with it

**Comment by MarshallAsch** [comment]
Would this be only visible to the `botomir-admin` or a different server admin / moderator role?

**Comment by rithik-c** [comment]
preferably the dedicated channel would be visible to any role the server
admin would like, but in the quick and easiest case, the channel could be
pre-setup by the server admins and roles for viewing permissions could be
assigned manually so all the bot has to do is log to that channel.

**Comment by MarshallAsch** [comment]
> so all the bot has to do is log to that channel.

That is going to be my initial approach since it should be the simplest to do, and there will be less 'magic' being done by botomir.

**Comment by rithik-c** [comment]
sounds great to me, so long as the basic functionality is there!

**Comment by MarshallAsch** [comment]
Do you have any specific format for the messages?

would something like this make sense?
```
DELETED MESSAGE
author: @user
Content: the message content
```

@SoorajModi thoughts?

**Comment by rithik-c** [comment]
the date/time as well as the channel of the message could also be useful.

the bcomp server's general format is
'{DELETE}[May 30 2021 19:48:00]<#general-chat>"I'm gonna delete this" '

then the edits would have {EDIT} and two quotation strings instead (before
and after). I'll leave the intricacies of formatting and whether you wanna
do it in a similar 1line fashion upto you.

**Comment by SoorajModi** [comment]
Yeah, I think including the timestamp would be useful. Alternatively, we can display this data via the frontend which might be easier for the moderators to interact with?

**Comment by rithik-c** [comment]
yeah I'd definetely prefer having everything seen on the frontend. you may
have misunderstood, that format is what's displayed on the bcomp server as
well, see the attached screenshot.

theres lines after lines of these, you can choose to format it however youd
like as long as its visibly easy to read and easy to sort through (i.e.
it's relatively easy to scroll to a certain dates messages or see messages
from a user or in a specific channel)
