### ISSUE TITLE
Heroku deprecation

### ISSUE THREAD

**Issue by SoorajModi** [Botomir/Botomir#322]
As of November 28, 2022, Heroku will no longer provide a free tier of hosting. Botomir is currently hosted on Heroku, and thus is a high impact issue. 

Two potential solutions:
- Stay with Heroku but shift to a paid plan
- Find an alternate platform with minimal (or ideally free) hosting

See [blog post](https://blog.heroku.com/next-chapter)

**Comment by MarshallAsch** [comment]
Done, migrated to personal server
